### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by esbobkov** [JamesSmith2/EthMonitoringLinux#1]
Monitoring periodically fails with exception:

`Unhandled exception in thread started by <function monitorMiner at 0x7f159654ca28>
Traceback (most recent call last):
  File "main.py", line 42, in monitorMiner
    sendToAPI(host, name, data)
  File "main.py", line 20, in sendToAPI
    conn.request("POST", "/api/update", params, headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known
^CTraceback (most recent call last):
  File "main.py", line 76, in <module>
    time.sleep(1)
`

**Comment by JamesSmith2** [comment]
Updated pushed out for it.
